### ISSUE TITLE
Disable Laravel CSRF protection for API

### ISSUE THREAD

**Issue by zachmay** [zachmay/inventory616#10]

**Comment by tttr222** [comment]
Hi Zach, we can't develop the POST api endpoints with the CSRF protection enabled. We'll figure out what to do to get it working, but just a reminder, thanks.

**Comment by hepengcs** [comment]
Hi,
Our team came across the same problem. Our solution is:  
1. Get  the CSRF Token generated by Laraval ( you only need to do this step once)
![image](https://cloud.githubusercontent.com/assets/11395718/6956787/513ee65e-d8c1-11e4-8276-da20cb0a8324.png)

2. Copy the CSRF Token to request header with key X-XSRF-TOKEN
![image](https://cloud.githubusercontent.com/assets/11395718/6956825/a55a3806-d8c1-11e4-981d-1cd96be0cc19.png)


Hope this helps.

**Comment by zachmay** [comment]
I've pushed a change to the master branch that disables the default CSRF protection scheme. You can merge master back into your team's branch(es) to grab the change.

@hepengcs Nice work. I didn't know you could use that header!

**Comment by zachmay** [comment]
Let me know if that fix works and we can close this one.

**Comment by akm-sabbir** [comment]
the problem has been fixed.  you can close the issue. thanks.
