### ISSUE TITLE
Need to check the raised exception due to integrity violation

### ISSUE THREAD

**Issue by akm-sabbir** [zachmay/inventory616#17]
is there a way to activate the laravel database constraint violation exception handling ? i have tried with the following 
Illuminate\Database\QueryException excep
but it did not work.
documentation says that i have to create a service provider. do i really need to create a service provider for this.
thanks

**Comment by zachmay** [comment]
@akm-sabbir I can't really answer this question without context. Can you point me to some code?

**Comment by akm-sabbir** [comment]
when i am trying to create the new checkin item with asset_tag is a unique id constraint in the table so duplicate item is throwing an exception and i would like to catch it,
	try{
						       Item::create([
										'asset_tag'          => $array_of_elem['asset_tag'],
										'name'               => $array_of_elem['item_name'],
										'funding_source'     => $array_of_elem['funding_source'],
										'item_type_id'       => (int)$device_id->id,
										'model'              => $array_of_elem['model'],
										'cpu'                => $array_of_elem['cpu'],
										'ram'                => $array_of_elem['ram'],
										'hard_disk'          => $array_of_elem['hard_disk'],
										'os'                 => $array_of_elem['os'],
										'administrator_flag' => (bool)$array_of_elem['administrator_flag'],
										'teacher_flag'       => (bool)$array_of_elem['teacher_flag'],
										'student_flag'       => (bool)$array_of_elem['student_flag'],
										'institution_flag'   => (bool)$array_of_elem['institution_flag']
								]);
						}catch ( Illuminate\Database\QueryException $e) {
								var_dump($e->errorInfo );
						}catch(Exception $ex){
							return Response("duplicate asset tag",404 );
						}

**Comment by zachmay** [comment]
@akm-sabbir Make a branch that has this code in it and tell me how to reproduce the issue, including what you expect to happen and what actually happens for you. Otherwise, I can't really answer your question.

**Comment by akm-sabbir** [comment]
i found an alternative solution. sorry to bother you. i was not explicit in my problem presentation. you can close it. thanks

**Comment by zachmay** [comment]
@akm-sabbir No bother, it's just usually best to make it as easy as possible to reproduce a problem.

What was your solution?
