### ISSUE TITLE
body content resolution

### ISSUE THREAD

**Issue by akm-sabbir** [zachmay/inventory616#19]
Hi Zack, what exactly i have to send through the body. right now i am sending asset_tag and room_id in a json format by using body and post method. then searching the database whether they exist or not and returning the information according to. 
thanks
Sabbir

**Comment by zachmay** [comment]
I don't really understand the question. What exactly are you trying to do?

**Comment by akm-sabbir** [comment]
it says "Create a new check-in resource for the specified option, based on the data in the request body (in particular, the room ID)" so based on the data in the request body. so what will be the data in the request body ? I just need that clarification. So i am trying to create a new checkin history and insert a new record in the check in table if the information provided by the request body of the post request is valid. such as if the asset_tag and room no exist or the asset_tag exist.

**Comment by zachmay** [comment]
OK, so we're trying to create a new record in the check-in table.

What are the fields on the check-in table: the table's primary key `id`, item ID, room ID, created-at timestamp, and updated timestamp. The time stamp fields and primary key are handled by the framework, so we only need an item ID and a room ID.

The URL of this API end-point already has the item ID, so we have access to that.

That leaves only one field that needs to be described in the body of the POST request: the room ID.

You can safely assume that the body is encoded as JSON and that the field containing the room ID is `room_id`. Of course, you need to check that `room_id` corresponds to a room that actually exists in the system. If it doesn't, you should return a 400 response (Bad Request), which we discussed last Wednesday in class.

**Comment by akm-sabbir** [comment]
Now I am clarified. thanks. sorry to bother you.

**Comment by zachmay** [comment]
Answering questions is what I'm here for. :)

**Comment by akm-sabbir** [comment]
I have an another question. what if the history already exist with the item_id and room_id ? should i create an another one ? or i just gonna ignore the fact ?

**Comment by zachmay** [comment]
As the design document states, the check-in table forms a history of rooms where the a given item inventory has been scanned, so yes, if an item is scanned time after time in the same room, there will be many check-ins with the same item and room. The primary key and timestamps will be different.

**Comment by akm-sabbir** [comment]
okay got that. I think you can close this issue.
