### ISSUE TITLE
Not able to check the api endpoint for inventory

### ISSUE THREAD

**Issue by anirban15** [zachmay/inventory616#20]
Hi Zach, 
We are  trying to look at http://192.168.33.99/api/inventory and we are getting the following error
NotFoundHttpException in RouteCollection.php line 145:

Kindly advise.

The VM is up and running

**Comment by zachmay** [comment]
What branch are you working with? Have you confirmed that it has team 4's commits that implement that endpoint?

**Comment by anirban15** [comment]
We are working with Team 4 API

**Comment by anirban15** [comment]
We are checking with Team 4 to see that they commited
