### ISSUE TITLE
query about room resource creation

### ISSUE THREAD

**Issue by akm-sabbir** [zachmay/inventory616#21]
i am trying to create a new room resource based on  a building id. my query is can a room of a building be assigned to multiple people or just to a single man/woman.

**Comment by zachmay** [comment]
There's the only assignment is just a free text field to describe whose room it is. They can basically put whatever they want in there.

**Comment by akm-sabbir** [comment]
ok got that. thanks. you can close the issue.

**Comment by akm-sabbir** [comment]
Hi Zack one more question what should be the response after successful post method or put method execution ?  200 ok. i am doing the redirection to another page.

**Comment by zachmay** [comment]
A successful POST should create a new record, so it should return 201 Created. A successful PUT just updated an existing record, so it should return 200 OK.
