### ISSUE TITLE
Api Endpoints - Facilities Managements questions

### ISSUE THREAD

**Issue by lcph222** [zachmay/inventory616#23]
Hi,

Can you clarify the different between "Retrieve a representation of the specified room resource " and "An individual room's collection of inventory items". 

Also for "/buildings" URL - "Retrieve a listing of all existing building resources. Should support a query parameter "search" that accepts a string by which results can be filtered," Is something like this what you were thinking about: /building:filter_string ? 

thanks,
Luan

**Comment by zachmay** [comment]
A room resource is just the details pertaining to a given room: it's ID, name, description, created date, and updated date. This is the resource pointed to a URL like `/api/buildings/:building-id/rooms/:room-id`.

Associated with each room resource is another resource: a collection of inventory items assigned to that room. Doing a GET on that resource should return a JSON list containing a JSON object representing each of the inventory items whose most recent check-in is in that room.
