### ISSUE TITLE
API - Inventory Check-ins

### ISSUE THREAD

**Issue by zachmay** [zachmay/inventory616#3]
Implement the endpoints listed under [Item Check-in History](../wiki/API-Endpoints#item-check-in-history) on the API endpoints page.

Please follow the [general guidelines for RESTful API development](../wiki/API-Development-Guidelines).

**Comment by akm-sabbir** [comment]
hi Zack how r u doing ? i have tried to clone the inventory616.git to my local machine but it is giving me the following permission denial error. i have tried both in linux and windows. can u give me some clue. thanks

git clone git@github.com:zachmay/inventory616.git

Cloning into 'inventory616'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).

**Comment by zachmay** [comment]
@akm-sabbir Have you [set up SSH keys for your GitHub account](https://help.github.com/articles/generating-ssh-keys/#platform-all)?

**Comment by akm-sabbir** [comment]
certainly not. thanks. i will let you know if i get some other problems.

**Comment by zachmay** [comment]
@akm-sabbir No problem. Let me know if that doesn't work for you.

**Comment by akm-sabbir** [comment]
it works thanks

**Comment by zachmay** [comment]
@akm-sabbir Good to hear.

**Comment by akm-sabbir** [comment]
Hi Zack i am having problem ssh into VM. vagrant ssh is not working. when i install the VM it did ask me for password configuration. i tried to ssh using putty and user name vagrant to 192.168.33.99 but it is asking me for password which i dont know. the public key is too large to use it as a password.

**Comment by zachmay** [comment]
What error do you get when you run "vagrant ssh"?

**Comment by akm-sabbir** [comment]
i used git mingw32 now its okay, i run linux in VM therefore i used the windows as host. previously i used the windows command prompt therefore it did not work may be.
