### ISSUE TITLE
Front-End: Foundations for JavaScript

### ISSUE THREAD

**Issue by zachmay** [zachmay/inventory616#8]
We are going to use the Backbone JS framework to create the user interface. Before we can really do any work with that, though, we need to do some ground work:

- Review Backbone documentation, tutorials, etc.
- Set up the Backbone framework. Make sure we have all the correct JS files in the `public/` directory.
- Set up routing. We just need to demonstrate that can load up the index page and get a link to fire a specific piece of JS code using Backbone's routing system.
- Try implementing a simple screen using Backbone but with mocked data (since the APIs aren't ready).

You may want to confer with @sjcurt02.

**Comment by zachmay** [comment]
Hey, I don't see a branch from you guys, so we can't make any comments!

**Comment by harika05** [comment]
hey, we are sorry about the confusion. I pushed the code without creating any branch. Learnt how to do it now. once again sorry about it.

**Comment by ghost** [comment]
@zachmay Hi Zach.. what is the endpoint API for pushing the data?

**Comment by zachmay** [comment]
@nedjem For pushing what data?

**Comment by ghost** [comment]
@zachmay For pushing inventory data..like asset tags etc

**Comment by zachmay** [comment]
@nedjem For creating a new inventory item record or updating an existing one? All that's in the documentation.

**Comment by ghost** [comment]
@zachmay For creating a new one..Thanks,will look in the documentation.

**Comment by harika05** [comment]
@zachmay When we are trying to post the inventory data into api/inventory end point, we are getting the following error (Failed to load resource: the server responded with a status of 500 (Internal Server Error). Can you please guide us regarding this issue. Thanks!

**Comment by zachmay** [comment]
What are you sending in the body of the request?

**Comment by harika05** [comment]
All the attributes of the inventory(asset_tag, name, funding_source...)
