### ISSUE TITLE
Test Suite - Documentation

### ISSUE THREAD

**Issue by zachmay** [zachmay/inventory616#9]
Produce a document describing test cases you think would be appropriate for all of [the API's endpoints as described on the wiki page](https://github.com/zachmay/inventory616/wiki/API-Endpoints#facilities-management).

This will require a good understanding of the Phase I design and REST architecture, but I (@zachmay) am available to answer questions, clarify things, and offer suggestions.

**Comment by pjlinton** [comment]
Guys, as Zach mentioned, you should be able to look at the Phase I design and produce a document with a list of test cases for each API endpoint.

**Comment by zachmay** [comment]
@liudw9094 @lixinchengdu @huazhewang @zhangyimc How's this document going?
